// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv7HX6ObEjKFVTgqcE16nX6Gs_htgtkqQ',
    appId: '1:555282151946:web:3fddc0c37dc93a8dc4fdf3',
    messagingSenderId: '555282151946',
    projectId: 'myapp-ashutosh',
    authDomain: 'myapp-ashutosh.firebaseapp.com',
    storageBucket: 'myapp-ashutosh.appspot.com',
    measurementId: 'G-7NL72E9TVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNK0dSpJBRDBNkwxjgsSk12QEVvbXT2YA',
    appId: '1:555282151946:android:a77f1f874925c916c4fdf3',
    messagingSenderId: '555282151946',
    projectId: 'myapp-ashutosh',
    storageBucket: 'myapp-ashutosh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOYpThSUR8vqAepH4WrAH9bm7bMLgP5l0',
    appId: '1:555282151946:ios:40b2e3cbfeea4becc4fdf3',
    messagingSenderId: '555282151946',
    projectId: 'myapp-ashutosh',
    storageBucket: 'myapp-ashutosh.appspot.com',
    iosClientId: '555282151946-g5jbbsfjeuf8b4hpg5afqtkjs3f6e0ni.apps.googleusercontent.com',
    iosBundleId: 'in.ashutosh799',
  );
}
